config/routes.rb
Rails.application.routes.draw do
  root to: 'tables#index'
  resources :tables

  resources :dish_and_drinks , only: [:index, :update, :show] do
    get :bar, on: :collection
    get :dishes, on: :collection
    get :search, on: :collection
    get :create
  end
  resources :feedbacks_and_suggestions, only: [:index, :new, :create]

  resources :payments, only: [:index] do
    member do
      get :pay
      post :pay
    end
  end

  resources :account, only: [:index]
  delete "/logout", to: "account#logout", as: :logout

  resources :employees, only: [:index, :show, :create, :update, :destroy] do
    get :create
  end

  resources :chip_baskets, only: [:index, :create, :update, :destroy]
  resources :orders, only: [:create, :update, :show] do
    member do
      patch :accept_order
      patch :mark_paid
    end
    patch 'mark_dish_done/:order_item_id', to: 'orders#mark_dish_done', as: :mark_dish_done
  end

  resources :managers do
    get :used_ingredients, on: :collection
    get :popular_dish, on: :collection
    get :tables_served_by_a_waitor, on: :collection
    get :waitor_of_tables, on: :collection
    patch :waitor_of_tables
    get :dish_and_drink, on: :collection
    get :table, on: :collection
    get :show
  end
end

app/models/add_table_to_order.rb
class AddTableToOrder < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/chip_basket.rb
class ChipBasket < ApplicationRecord
  belongs_to :table
  has_many :chip_basket_items, dependent: :destroy

  def full_price
    chip_basket_items.map {|chip_basket_item| chip_basket_item.number_of_dish * chip_basket_item.dish_and_drink.price }.sum
  end
end

app/models/chip_basket_item.rb
class ChipBasketItem < ApplicationRecord
  belongs_to :dish_and_drink
  belongs_to :chip_basket

end

app/models/client.rb
class Client < ApplicationRecord
  has_one :feedback_and_suggestion
  has_one :table
end

app/models/dish_and_drink.rb
class DishAndDrink < ApplicationRecord
  has_many :order_items, dependent: :destroy
  has_many :ingredients, dependent: :destroy
  has_many :chip_baskets_items, dependent: :destroy
  has_one_attached :image
end

app/models/employee.rb
class Employee < ApplicationRecord
  has_many :orders
  has_many :tables

  def full_name
    "#{last_name} #{first_name} #{parent_name}".strip
  end
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  belongs_to :dish_and_drink
end

app/models/join_table.rb
class JoinTable < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :table
  belongs_to :employee, optional:true
  has_many :order_items, dependent: :destroy

  def full_price
    order_items.map {|order_item| order_item.number_of_dishes * order_item.dish_and_drink.price }.sum
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :dish_and_drink
  has_many :orders
end

app/models/table.rb
class Table < ApplicationRecord
  # TODO: change order to orders
  has_many :order
  belongs_to :employee, optional:true
  belongs_to :client
  has_one :chip_basket
end

app/controllers/dish_and_drinks_controller.rb
class DishAndDrinksController < ApplicationController
  before_action :set_dishes_and_drinks, only: %i[dishes bar]
  before_action :set_dish_and_drink, only: [:show, :update]

  def index
    table = session[:table_number]
    @order = Order.where(table_id: table).where.not(order_status: "Сплачено").order(created_at: :desc).first
    @employee = Employee.find_by(id: session[:employee_id])
  end

  def bar
    @category = 'Drink'
    filter_by_category
  end

  def dishes
    @category = 'Food'
    filter_by_category
  end

  def show

  end

  def create
    @dish_and_drink = DishAndDrink.create(menu_params)
  end

  def update
    if @dish_and_drink.present?
      @dish_and_drink.update(menu_params)
    end
  end

  # def search
  #   @search = DishAndDrink.ransack(params[:q])
  #   @search_dishes = @search.result(distinct: true)
  #   flash[:notice] = "Pезультати пошуку" if params[:q].present?
  # end

  private

  def menu_params
    params.require(:dish_and_drink).permit(:name, :grams, :category, :category_type, :price)
  end

  def set_dish_and_drink
    @dish_and_drink = DishAndDrink.find_by(id: params[:id])
  end

  def set_dishes_and_drinks
    @menu = DishAndDrink.all
  end

  def filter_by_category
    if params[:category].present?
      @filter_category = @menu.where(category_type: params[:category])
    else
      @filter_category = @menu.where(category: @category)
    end
  end
end

app/helpers/account_helper.rb
module AccountHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/dish_and_drinks_helper.rb
module DishAndDrinksHelper
end

app/helpers/employee_helper.rb
module EmployeeHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/manager_helper.rb
module ManagerHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/tables_helper.rb
module TablesHelper
end

app/views/dish_and_drinks/_content.html.erb
<div class="btn-category">
  <%= link_to "Меню", request.path, class: "btn" %>
  <% @menu.where(category: @category).pluck(:category_type).uniq.each do |category|%>
    <%= link_to category, request.path + "?category=#{category}", class: "btn"%>
  <% end %>
</div>

<main class="dishes-content">
  <% @filter_category.pluck(:category_type).uniq.each do |category| %>
    <h2><%= category %></h2>
    <% @filter_category.where(category_type:category).uniq.each do |menu_item| %>
      <%= render partial: "dish_and_drinks/menu_item", locals: { menu_item: menu_item}%>
    <% end %>
  <% end %>
</main>

app/views/dish_and_drinks/_menu_item.html.erb
<div class="dish-content">
  <div class="about-dishes">
    <img src="https://images.pexels.com/photos/376464/pexels-photo-376464.jpeg?auto=compress&cs=tinysrgb&w=600" alt="Фото страви" class="dish-image">
    <div>
      <p class="name-dishes"><%= menu_item.name %></p>
      <p><%= menu_item.ingredients.map {|ingredient| ingredient.name }.join(", ") %></p>
      <p><%= menu_item.grams %> гр</p>
    </div>
  </div>
  <div class="create-cart-items">
    <p class="price-dish"><%= menu_item.price %> грн</p>
    <% unless session[:table_number].nil? %>
      <%= form_with url: chip_baskets_path, method: :post, local: true do |form| %>
        <%= hidden_field_tag :dish_and_drink_id, menu_item.id %>
        <div class="dish-ordering">
          <%= form.number_field :number_of_dish, min: 1, class: "quantity-input" %>
          <%= form.submit "Додати до кошику", class: "btn-add-to-cart" %>
        </div>
      <% end %>
    <% end %>
  </div>
</div>


app/views/dish_and_drinks/bar.html.erb
<div class="content">
  <div class="header-pages">
    <%= render partial: "layouts/header" , locals: {title: "Бар"}%>
    <%= button_to chip_baskets_path, class: "btn-cart", method: :get do %>
      <i class="fa-solid fa-cart-shopping"></i>
    <% end %>
  </div>
  <div class="dishes-content">
    <%= render partial: "dish_and_drinks/content", locals: { menu: @menu } %>
  </div>
</div>

app/views/dish_and_drinks/dishes.html.erb
<div class="content">
  <div class="header-pages">
    <%= render partial: "layouts/header" , locals: {title: "Меню"}%>
    <%= button_to chip_baskets_path, class: "btn-cart", method: :get do %>
      <i class="fa-solid fa-cart-shopping"></i>
    <% end %>
  </div>
  <div class="dishes-content">
    <%= render partial: "dish_and_drinks/content", locals: { menu: @menu } %>
  </div>
</div>

app/views/dish_and_drinks/index.html.erb
<div class="navigation">
  <img class="logotype" src="/images/logotype.jpg" alt="Зображення логотипу ресторана">
 <% if session[:employee_id] %>
    <div class="login-form">
      <span class="login"><%= session[:employee_name] %></span>
      <div class="btn-employee">
        <% if @employee&.job_title == "Керівник" %>
          <%= button_to "Адмін панель", managers_path, class: "btn-logout", method: :get %>
        <% end %>
        <%= button_to "Вийти", logout_path, class: "btn-logout", method: :delete %>
      </div>
    </div>
  <% else %>
    <%= button_to account_index_path, method: :get, class: "btn-account" do %>
      <i class="fa-solid fa-circle-user"></i>
    <% end %>
  <% end %>
</div>
<header class="header">
  <nav class="nav">

  </nav>
  <h1 class="name-restaurant" style="font-family: 'Times New Roman', Times, serif;">Le Jardin</h1>
  <p class="describe">Ресторан французької кухні</p>
</header>

<main class="main-content">
  <div class="title-content">
    <p class="text-ttl"><span>DIGITAL MENU</span></p>
  </div>

  <div class="chapter">
    <p class="chapter-menu"><%= link_to 'МЕНЮ/MENU',  dishes_dish_and_drinks_path, class:'chapter-menu'%></p>
    <%= button_to dishes_dish_and_drinks_path, method: :get, class: "btn-transition" do %>
      <i class="fa-solid fa-circle-chevron-right"></i>
    <% end %>
  </div>

  <div class="chapter">
    <p class="chapter-menu"><%= link_to 'БАР/BAR', bar_dish_and_drinks_path, class:'chapter-menu'%></p>
    <%= button_to bar_dish_and_drinks_path, method: :get, class: "btn-transition" do %>
      <i class="fa-solid fa-circle-chevron-right"></i>
    <% end %>
  </div>

  <div class="chapter">
    <p class="chapter-menu"><%= link_to 'ОПЛАТА/PAYMENT',  payments_path, class:'chapter-menu'%></p>
    <%= button_to payments_path, method: :get, class: "btn-transition" do %>
      <i class="fa-solid fa-circle-chevron-right"></i>
    <% end %>
  </div>

  <% if session[:employee_id] %>
    <div class="chapter">
      <p class="chapter-menu"><%= link_to 'ЗАМОВЛЕННЯ',  @order, class:'chapter-menu'%></p>
      <%= button_to @order, method: :get, class: "btn-transition" do %>
        <i class="fa-solid fa-circle-chevron-right"></i>
      <% end %>
    </div>
    <div class="chapter">
      <p class="chapter-menu"><%= link_to 'Обрати столик', tables_path, class:'chapter-menu'%></p>
      <%= button_to tables_path, method: :get, class: "btn-transition" do %>
        <i class="fa-solid fa-circle-chevron-right"></i>
      <% end %>
    </div>
  <% end %>

  <div class="title-content">
    <p class="text-ttl"><span>ПОСИЛАННЯ</span></p>
  </div>

  <div class="chapter">
    <p class="chapter-menu"><%= link_to 'Надіслати відгук', feedbacks_and_suggestions_path, class:'chapter-menu'%></p>
    <%= button_to feedbacks_and_suggestions_path, method: :get, class: "btn-transition" do %>
      <i class="fa-solid fa-circle-chevron-right"></i>
    <% end %>
  </div>
</main>

app/views/dish_and_drinks/show.html.erb
<%= render partial: "managers/header", locals: {title: "Страви та напої"} %>
<div>

  <%= form_with model: @dish_and_drink, method: :put do |form| %>
    <div class="dish-and-drink-content">
      <div class="dish-and-drink-forms">
        <div class="form-update">
          <div>
            <p class="dish-and-drink-text">Назва страви: </p>
            <%= form.text_field :name, value: @dish_and_drink.name, class: "dish-and-drink-form"%>
          </div>
          <div >
            <p class="dish-and-drink-text">Грам: </p>
            <%= form.number_field :grams,  value: @dish_and_drink.grams, class: "dish-and-drink-form"%>
          </div>
          <div>
            <p class="dish-and-drink-text">Категорія(Food or Drink): </p>
            <%= form.text_field :category, value: @dish_and_drink.category, class: "dish-and-drink-form"%>
          </div>
          <div>
            <p class="dish-and-drink-text">Категорія страви: </p>
            <%= form.text_field  :category_type, value: @dish_and_drink.category_type, class: "dish-and-drink-form"%>
          </div>
          <div>
            <p class="dish-and-drink-text">Ціна: </p>
            <%= form.number_field  :price, value: @dish_and_drink.price, class: "dish-and-drink-form" %>
          </div>
        </div>
      </div>
      <div class="btn-dish-and-drink-add">
        <%= form.submit "Оновити" , class: "btn-add-menu"%>
      </div>
    </div>
  <% end %>
</div>