config/routes.rb
Rails.application.routes.draw do
  root to: 'tables#index'
  resources :tables

  resources :dish_and_drinks , only: [:index, :update, :show] do
    get :bar, on: :collection
    get :dishes, on: :collection
    get :search, on: :collection
    get :create
  end
  resources :feedbacks_and_suggestions, only: [:index, :new, :create]

  resources :payments, only: [:index] do
    member do
      get :pay
      post :pay
    end
  end

  resources :account, only: [:index]
  delete "/logout", to: "account#logout", as: :logout

  resources :employees, only: [:index, :show, :create, :update, :destroy] do
    get :create
  end

  resources :chip_baskets, only: [:index, :create, :update, :destroy]
  resources :orders, only: [:create, :update, :show] do
    member do
      patch :accept_order
      patch :mark_paid
    end
    patch 'mark_dish_done/:order_item_id', to: 'orders#mark_dish_done', as: :mark_dish_done
  end

  resources :managers do
    get :used_ingredients, on: :collection
    get :popular_dish, on: :collection
    get :tables_served_by_a_waitor, on: :collection
    get :waitor_of_tables, on: :collection
    patch :waitor_of_tables
    get :dish_and_drink, on: :collection
    get :table, on: :collection
    get :show
  end
end

app/models/add_table_to_order.rb
class AddTableToOrder < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/chip_basket.rb
class ChipBasket < ApplicationRecord
  belongs_to :table
  has_many :chip_basket_items, dependent: :destroy

  def full_price
    chip_basket_items.map {|chip_basket_item| chip_basket_item.number_of_dish * chip_basket_item.dish_and_drink.price }.sum
  end
end

app/models/chip_basket_item.rb
class ChipBasketItem < ApplicationRecord
  belongs_to :dish_and_drink
  belongs_to :chip_basket

end

app/models/client.rb
class Client < ApplicationRecord
  has_one :feedback_and_suggestion
  has_one :table
end

app/models/dish_and_drink.rb
class DishAndDrink < ApplicationRecord
  has_many :order_items, dependent: :destroy
  has_many :ingredients, dependent: :destroy
  has_many :chip_baskets_items, dependent: :destroy
  has_one_attached :image
end

app/models/employee.rb
class Employee < ApplicationRecord
  has_many :orders
  has_many :tables

  def full_name
    "#{last_name} #{first_name} #{parent_name}".strip
  end
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  belongs_to :dish_and_drink
end

app/models/join_table.rb
class JoinTable < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :table
  belongs_to :employee, optional:true
  has_many :order_items, dependent: :destroy

  def full_price
    order_items.map {|order_item| order_item.number_of_dishes * order_item.dish_and_drink.price }.sum
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :dish_and_drink
  has_many :orders
end

app/models/table.rb
class Table < ApplicationRecord
  # TODO: change order to orders
  has_many :order
  belongs_to :employee, optional:true
  belongs_to :client
  has_one :chip_basket
end

app/controllers/managers_controller.rb
class ManagersController < ApplicationController
  before_action :set_order, only: [:show]
  before_action :date_filter, only: [:used_ingredients, :popular_dish, :tables_served_by_a_waitor]
  def index
    @manager_id = Employee.find_by(job_title: "Керівник")
  end

  def used_ingredients
    @group_dish = @order.group(:dish_and_drink_id).count
    @ingredients_count = Hash.new(0)

    @group_dish.each do |dish_id, count|
      @ingredients = Ingredient.where(dish_and_drink_id: dish_id)
      @ingredients.each do |ingredient|
        @ingredients_count[ingredient.name] += ingredient.grams * count
      end
    end
  end

  def popular_dish
    order_items = OrderItem.where(created_at: @start_date..@end_date)
    @group_dish = order_items.group(:dish_and_drink_id).count
    max_count = @group_dish.values.max
    @max_dishes = @group_dish.select { |dish_id, count| count == max_count }
    @max_dish_names = DishAndDrink.where(id: @max_dishes.keys).pluck(:name)

  end

  def tables_served_by_a_waitor
    orders = Order.where(created_at: @start_date..@end_date)
    @group_employee = orders.group(:employee_id).count
    @employees = Employee.where(id: @group_employee.keys)
  end

  # def waitor_of_tables
  #   @table = Table.all
  #   @tables = Table.where(table_number: params[:table_number])
  #   @employee = Employee.find_by(id: params[:employee_id], job_title: "Офіціант")
  #   if @tables.present?
  #     @tables.update(
  #       employee_id: @employee.id
  #     )
  #   end
  # end

  def dish_and_drink
    @dish_and_drink = DishAndDrink.all
  end

  def table
    @tables = Table.all
    @employee = Employee.where(job_title: "Офіціант")
  end

  def create

  end

  def update
    @table = Table.find(params[:id])
    if @table.update(employee_id: params[:table][:employee_id])
      redirect_to table_managers_path
    end
  end

  def destroy

  end

  def show
    @tables = Table.find_by(table_number: params[:id])

    redirect_to manager_show_path(@table)
  end

  private
  def set_order
    @order = Order.all
    @order_items = @order.order_items.all
  end
  def date_filter
    d = DateTime.now
    @start_date = params[:start_date].present? ? Date.parse(params[:start_date]) : d.beginning_of_month
    @end_date = params[:end_date].present? ? Date.parse(params[:end_date]) : d.end_of_month
    @order = OrderItem.where(created_at: @start_date..@end_date)
  end
end

app/helpers/account_helper.rb
module AccountHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/employee_helper.rb
module EmployeeHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/manager_helper.rb
module ManagerHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/tables_helper.rb
module TablesHelper
end

app/views/managers/_header.html.erb
<div class="header-managers-page">
  <%= button_to managers_path, method: :get, class: "btn-home" do %>
    <i class="fa-solid fa-circle-chevron-left"></i>
  <% end %>
  <h1><%= title %></h1>
</div>

app/views/managers/dish_and_drink.html.erb
<%= render partial: "managers/header", locals: {title: "Страви та напої"} %>
<div class="menu-content">
  <% @dish_and_drink.each do |dish_and_drink| %>
    <%= button_to dish_and_drink_path(dish_and_drink), method: :get, class: "dish-and-drink-btn" do %>
      <%= dish_and_drink.name %>
    <% end %>
  <% end %>
</div>
<%#= form_with model: @dish_and_drink, url: dish_and_drinks_path, method: :post do |form| %>
<!--  <div>-->
<!--    <p>Назва страви: </p>-->
    <%#= form.text_field :name%>
<!--  </div>-->
<!--  <div>-->
<!--    <p>Грам: </p>-->
    <%#= form.text_field :grams %>
<!--  </div>-->
<!--  <div>-->
<!--    <p>Категорія (Food or Drink): </p>-->
    <%#= form.text_field :category %>
<!--  </div>-->
<!--  <div>-->
<!--    <p>Категорія страви: </p>-->
    <%#= form.text_field :category_type %>
<!--  </div>-->
<!--  <div>-->
<!--    <p>Ціна: </p>-->
    <%#= form.text_field :price %>
<!--  </div>-->
  <%#= form.submit "Додати нову страву" %>
<%# end %>


app/views/managers/index.html.erb
<div class="button-manager">
  <%= render partial: "layouts/header", locals: {title: "Панель керівника"} %>
  <div>
    <%= button_to 'Співробітники', employees_path, method: :get, class: "btn-manager"%>

    <%= button_to 'Страви та напої',  dish_and_drink_managers_path, method: :get, class: "btn-manager" %>

    <%= button_to 'Згенерувати звіт "Використані продукти"', used_ingredients_managers_path, method: :get, class: "btn-manager" %>

    <%= button_to 'Згенерувати звіт "Найпопулярніші страви"',  popular_dish_managers_path, method: :get, class: "btn-manager" %>

    <%= button_to 'Згенерувати звіт "К-ть обслуговані замовлення офіціантами"', tables_served_by_a_waitor_managers_path, method: :get, class: "btn-manager" %>
  </div>
</div>

app/views/managers/popular_dish.html.erb
<%= render partial: "managers/header", locals: {title: "Найпопулярніші страви"} %>
<p class="text-content-header">Дані</p>
<%= form_with url: popular_dish_managers_path, method: :get, local:true do%>
  <div>
    <div class="form-data-content">
      <label class="text-content-product" for="start_date">з</label>
      <%= date_field_tag :start_date, params[:start_date], class: "form-data"%>
    </div>
  </div>
  <div>
    <div class="form-data-content">
      <label class="text-content-product" for="start_date">по</label>
      <%= date_field_tag :end_date, params[:end_date], class: "form-data" %>
    </div>
  </div>
  <div class="btn-data-search">
    <%= submit_tag "Знайти", class: "btn-data"%>
  </div>
<% end %>

<div class="manager_content">
<% @max_dish_names.each do |dish_name| %>
  <p class="ingredient-dish"><%= dish_name %></p>
<% end %>
</div>

app/views/managers/tables_served_by_a_waitor.html.erb
<%= render partial: "managers/header", locals: {title: "Кількість обслугованих замовлень співробітниками"} %>
<p class="text-content-header">Дані</p>
<%= form_with url: tables_served_by_a_waitor_managers_path, method: :get, local:true do%>
  <div>
    <div class="form-data-content">
      <label class="text-content-product" for="start_date">з</label>
      <%= date_field_tag :start_date, params[:start_date], class: "form-data"%>
    </div>
  </div>
  <div>
    <div class="form-data-content">
      <label class="text-content-product" for="start_date">по</label>
      <%= date_field_tag :end_date, params[:end_date], class: "form-data" %>
    </div>
  </div>
  <div class="btn-data-search">
    <%= submit_tag "Знайти", class: "btn-data"%>
  </div>
<% end %>

<div class="manager_content">
<% @employees.each do |employee| %>
  <p class="ingredient-dish">Офіціант: <%= employee.full_name %> обслугував замовлень: <%= @group_employee[employee.id] %></p>
<% end %>
</div>

app/views/managers/used_ingredients.html.erb
<%= render partial: "managers/header", locals: {title: "Використані інгредієнти"} %>
<p class="text-content-header">Дані</p>
<%= form_with url: used_ingredients_managers_path, method: :get, local:true do%>
  <div>
    <div class="form-data-content">
      <label class="text-content-product" for="start_date">з</label>
      <%= date_field_tag :start_date, params[:start_date], class: "form-data"%>
    </div>
  </div>
  <div>
    <div class="form-data-content">
      <label class="text-content-product" for="start_date">по</label>
      <%= date_field_tag :end_date, params[:end_date], class: "form-data" %>
    </div>
  </div>
  <div class="btn-data-search">
    <%= submit_tag "Знайти", class: "btn-data"%>
  </div>
<% end %>

<div class="manager_content">
  <p class="ingredient-title">Продукт</p>
  <p class="ingredient-title">Грам</p>
</div>
<% @ingredients_count.each do |name, count| %>
  <div class="manager_content">
    <p class="ingredient-dish"><%= name %></p>
    <p class="ingredient-dish"><%= count %></p>
  </div>
<% end %>

app/views/managers/waitor_of_tables.erb
<%= render partial: "managers/header", locals: {title: "Столики"} %>
<% @table.each do |table| %>
  <% employee = table.employee %>
    <p>Столик №<%= table.table_number %></p>
    <p>Cпівробітник що відповідає: <%= employee.full_name %></p>
  <%= form_with url: waitor_of_tables_managers_path(table_number: table.table_number), method: :patch, local: true do |form| %>
    <%= form.label :employee_id, "Оберіть офіціанта" %>
    <%= form.collection_select :employee_id, @employee, :id, :full_name, prompt: "Оберіть офіціанта" %>
    <%= form.submit "Додати офіціанта" %>
  <% end %>
<% end %>