config/routes.rb
Rails.application.routes.draw do
  root to: 'tables#index'
  resources :tables

  resources :dish_and_drinks , only: [:index, :update, :show] do
    get :bar, on: :collection
    get :dishes, on: :collection
    get :search, on: :collection
    get :create
  end
  resources :feedbacks_and_suggestions, only: [:index, :new, :create]

  resources :payments, only: [:index] do
    member do
      get :pay
      post :pay
    end
  end

  resources :account, only: [:index]
  delete "/logout", to: "account#logout", as: :logout

  resources :employees, only: [:index, :show, :create, :update, :destroy] do
    get :create
  end

  resources :chip_baskets, only: [:index, :create, :update, :destroy]
  resources :orders, only: [:create, :update, :show] do
    member do
      patch :accept_order
      patch :mark_paid
    end
    patch 'mark_dish_done/:order_item_id', to: 'orders#mark_dish_done', as: :mark_dish_done
  end

  resources :managers do
    get :used_ingredients, on: :collection
    get :popular_dish, on: :collection
    get :tables_served_by_a_waitor, on: :collection
    get :waitor_of_tables, on: :collection
    patch :waitor_of_tables
    get :dish_and_drink, on: :collection
    get :table, on: :collection
    get :show
  end
end

app/models/add_table_to_order.rb
class AddTableToOrder < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/chip_basket.rb
class ChipBasket < ApplicationRecord
  belongs_to :table
  has_many :chip_basket_items, dependent: :destroy

  def full_price
    chip_basket_items.map {|chip_basket_item| chip_basket_item.number_of_dish * chip_basket_item.dish_and_drink.price }.sum
  end
end

app/models/chip_basket_item.rb
class ChipBasketItem < ApplicationRecord
  belongs_to :dish_and_drink
  belongs_to :chip_basket

end

app/models/client.rb
class Client < ApplicationRecord
  has_one :feedback_and_suggestion
  has_one :table
end

app/models/dish_and_drink.rb
class DishAndDrink < ApplicationRecord
  has_many :order_items, dependent: :destroy
  has_many :ingredients, dependent: :destroy
  has_many :chip_baskets_items, dependent: :destroy
  has_one_attached :image
end

app/models/employee.rb
class Employee < ApplicationRecord
  has_many :orders
  has_many :tables

  def full_name
    "#{last_name} #{first_name} #{parent_name}".strip
  end
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  belongs_to :dish_and_drink
end

app/models/join_table.rb
class JoinTable < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :table
  belongs_to :employee, optional:true
  has_many :order_items, dependent: :destroy

  def full_price
    order_items.map {|order_item| order_item.number_of_dishes * order_item.dish_and_drink.price }.sum
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :dish_and_drink
  has_many :orders
end

app/models/table.rb
class Table < ApplicationRecord
  # TODO: change order to orders
  has_many :order
  belongs_to :employee, optional:true
  belongs_to :client
  has_one :chip_basket
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :accept_order, :mark_dish_done, :mark_paid]

  def create
    table = session[:table_number]
    @chip_basket = ChipBasket.find_by(table_id: table)
    @order = Order.find_or_create_by(
      table_id: @chip_basket.table_id,
      employee_id: nil,
      order_status: "Оформлено"
    )

    if @order.present?
      @chip_basket.chip_basket_items.each do |item|
        OrderItem.create(
          order_id: @order.id,
          dish_and_drink_id: item.dish_and_drink_id,
          number_of_dishes: item.number_of_dish,
          dish_status: "Готується"
        )

        @chip_basket.chip_basket_items.destroy_all
      end
    end
  end

  def show
    @order_items = @order.order_items
    @employee_name = session[:employee_name]
  end

  def accept_order
    if @order.present? && session[:employee_id]
      @order.update(
        employee_id: current_employee.id,
        order_status: "Прийнято"
      )
    end
    redirect_to @order, notice: "Замовлення прийнято"
  end

  def mark_dish_done
    if @order.order_status == "Прийнято"
      @order_items = @order.order_items.find_by(id: params[:order_item_id])
      if @order_items.present?
        @order_items.update(
          dish_status: "Виконано",
          )
      end
    end
    redirect_to @order

    if @chip_basket.present?
      @chip_basket_item = @chip_basket.chip_basket_items.find_by(id: params[:id])

      if @chip_basket_item.present?
        @chip_basket_item.destroy
        redirect_to chip_basket_chip_baskets_path
      end
    end
  end

  def mark_paid
    @order_items = @order.order_items
    if @order.order_status == "Прийнято" && @order_items.all? { |item| item.dish_status == "Виконано" && @order.order_status != "Сплачено"}
      @order.update(
      order_status: "Сплачено",
      )
    end
    redirect_to dish_and_drinks_path
  end

  private

  def set_order
    table = session[:table_number]
    @order = Order.where(table_id: table).where.not(order_status: "Сплачено").first
  end

  def current_employee
    @current_employee ||= Employee.find(session[:employee_id]) if session[:employee_id]
  end
end

app/helpers/account_helper.rb
module AccountHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/employee_helper.rb
module EmployeeHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/manager_helper.rb
module ManagerHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/tables_helper.rb
module TablesHelper
end

app/views/orders/show.html.erb
<div>
  <%= render partial: "layouts/header", locals: {title: "Замовлення"} %>

  <% if @order.present? && @order.order_status != "Сплачено"%>
    <h3 class="header-cart">Ваше замовлення</h3>

    <% unless @order.employee_id.nil? %>
      <p class="text-dishes"><%= @employee_name %></p>
    <% end %>

    <div class="content-order">
      <% @order.order_items.each do |order_item| %>
        <% dish = order_item.dish_and_drink %>
        <div class="info-order">
          <div class="order-dishes">
            <p class="text-dishes-order"><%= dish.name %></p>
            <input type="number" value="<%= order_item.number_of_dishes %>" class="input-number-of-dishes">
            <p class="text-dishes"><%= dish.grams %> гр</p>
            <p class="text-dishes"><%= order_item.dish_status %></p>
            <p class="text-dishes"><%= dish.price * order_item.number_of_dishes %> грн</p>

            <% if @order.order_status == "Прийнято" && order_item.dish_status != "Виконано" %>
              <%= button_to order_mark_dish_done_path(@order, order_item_id: order_item.id), method: :patch do %>
                Виконано
              <% end %>
            <% end %>
          </div>
        </div>
      <% end %>

      <p class="dishes-describe">Загальна сума: <%= @order.full_price %> грн</p>

      <% if @order.order_status == "Оформлено" %>
        <div class="btn-order">
          <%= button_to accept_order_order_path(@order), method: :patch, class: "button-order" do %>
            Прийняти замовлення
          <% end %>
        </div>
      <% end %>

      <% if @order.order_items.all? { |item| item.dish_status == "Виконано" } && @order.order_status != "Сплачено" %>
        <%= button_to mark_paid_order_path(@order), method: :patch do %>
          Сплачено
        <% end %>

        <%= button_to payments_path(@order), method: :get do %>
          Сформувати рахунок
        <% end %>
      <% end %>
    </div>
  <% end %>
</div>