config/routes.rb
Rails.application.routes.draw do
  root to: 'tables#index'
  resources :tables

  resources :dish_and_drinks , only: [:index, :update, :show] do
    get :bar, on: :collection
    get :dishes, on: :collection
    get :search, on: :collection
    get :create
  end
  resources :feedbacks_and_suggestions, only: [:index, :new, :create]

  resources :payments, only: [:index] do
    member do
      get :pay
      post :pay
    end
  end

  resources :account, only: [:index]
  delete "/logout", to: "account#logout", as: :logout

  resources :employees, only: [:index, :show, :create, :update, :destroy] do
    get :create
  end

  resources :chip_baskets, only: [:index, :create, :update, :destroy]
  resources :orders, only: [:create, :update, :show] do
    member do
      patch :accept_order
      patch :mark_paid
    end
    patch 'mark_dish_done/:order_item_id', to: 'orders#mark_dish_done', as: :mark_dish_done
  end

  resources :managers do
    get :used_ingredients, on: :collection
    get :popular_dish, on: :collection
    get :tables_served_by_a_waitor, on: :collection
    get :waitor_of_tables, on: :collection
    patch :waitor_of_tables
    get :dish_and_drink, on: :collection
    get :table, on: :collection
    get :show
  end
end

app/models/add_table_to_order.rb
class AddTableToOrder < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/chip_basket.rb
class ChipBasket < ApplicationRecord
  belongs_to :table
  has_many :chip_basket_items, dependent: :destroy

  def full_price
    chip_basket_items.map {|chip_basket_item| chip_basket_item.number_of_dish * chip_basket_item.dish_and_drink.price }.sum
  end
end

app/models/chip_basket_item.rb
class ChipBasketItem < ApplicationRecord
  belongs_to :dish_and_drink
  belongs_to :chip_basket

end

app/models/client.rb
class Client < ApplicationRecord
  has_one :feedback_and_suggestion
  has_one :table
end

app/models/dish_and_drink.rb
class DishAndDrink < ApplicationRecord
  has_many :order_items, dependent: :destroy
  has_many :ingredients, dependent: :destroy
  has_many :chip_baskets_items, dependent: :destroy
  has_one_attached :image
end

app/models/employee.rb
class Employee < ApplicationRecord
  has_many :orders
  has_many :tables

  def full_name
    "#{last_name} #{first_name} #{parent_name}".strip
  end
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  belongs_to :dish_and_drink
end

app/models/join_table.rb
class JoinTable < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :table
  belongs_to :employee, optional:true
  has_many :order_items, dependent: :destroy

  def full_price
    order_items.map {|order_item| order_item.number_of_dishes * order_item.dish_and_drink.price }.sum
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :dish_and_drink
  has_many :orders
end

app/models/table.rb
class Table < ApplicationRecord
  # TODO: change order to orders
  has_many :order
  belongs_to :employee, optional:true
  belongs_to :client
  has_one :chip_basket
end

app/controllers/chip_baskets_controller.rb
class ChipBasketsController < ApplicationController
  def create
    table = session[:table_number]
    @chip_basket = ChipBasket.find_or_create_by(table_id: table)

    @chip_basket_item = @chip_basket.chip_basket_items.find_by(dish_and_drink_id: params[:dish_and_drink_id])

    if @chip_basket_item.present?
      @chip_basket_item.update(number_of_dish: @chip_basket_item.number_of_dish + params[:number_of_dish].to_i)
    else
      @chip_basket_item = ChipBasketItem.create(
        chip_basket: @chip_basket,
        dish_and_drink_id: params[:dish_and_drink_id],
        number_of_dish: params[:number_of_dish].to_i
      )
    end
  end

  def index
    table = session[:table_number]
    @chip_basket = ChipBasket.where(table_id: table).order(created_at: :desc).first
    @order = @chip_basket.table.order
    @total_price = @chip_basket.full_price
    if params[:table_id].present?
      flash[:notice] = "Ваше замовлення"
    end
  end

  def destroy
    table = session[:table_number]
    @chip_basket = ChipBasket.find_by(table_id: table)

    if @chip_basket.present?
      @chip_basket_item = @chip_basket.chip_basket_items.find_by(id: params[:id])

      if @chip_basket_item.present?
        @chip_basket_item.destroy
        redirect_to chip_baskets_path
      end
    end
  end
end

app/helpers/account_helper.rb
module AccountHelper
end

app/helpers/chip_basket_helper.rb
module ChipBasketHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/employee_helper.rb
module EmployeeHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/manager_helper.rb
module ManagerHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/tables_helper.rb
module TablesHelper
end

app/views/chip_baskets/index.html.erb
<div>
  <%= render partial: "layouts/header" , locals: {title: "Кошик"}%>
  <% if @chip_basket.present? %>
    <h3 class="header-order">Ваше замовлення</h3>
    <div class="content-cart">
      <% @chip_basket.chip_basket_items.each do |chip_basket_item| %>
        <% dish = chip_basket_item.dish_and_drink %>
        <div class="info-cart">
          <div class="order-dishes">
            <p class="text-dishes"><%= dish.name %></p>
            <input type="number" value="<%= chip_basket_item.number_of_dish %>" class="input-number-of-dishes">
            <p class="text-dishes"><%= dish.grams %> гр</p>
            <p class="text-dishes"><%= dish.price * chip_basket_item.number_of_dish %> грн</p>
            <%= button_to chip_basket_path(id: chip_basket_item.id, table_id: params[:table_id]), method: :delete, class: "btn-cart" do %>
              <i class="fa-solid fa-trash"></i>
            <% end %>
          </div>
        </div>
      <% end %>
      <p class="dishes-describe">Загальна сума: <%= @total_price %> грн</p>
      <div class="btn-cart">
        <%= button_to orders_path(table_id: params[:table_id]), method: :post, class: "button-order" do %>
          Оформити замовлення
        <% end %>
      </div>
    </div>
  <% end %>
</div>











